Repository bryanp/llhttp, pull requests merged in 2021-03, with the labels that each got.

#6 Update llhttp to 3.0.1
  LICENSE
  ext/llhttp/api.c
  ext/llhttp/http.c
  ext/llhttp/llhttp.c
  ext/llhttp/llhttp.h
  ext/llhttp/llhttp_ext.c
Labels: commit.changelog, commit.type.chg

#7 Return an error status from the appropriate callbacks
  benchmarks/mri/Gemfile
  benchmarks/mri/run.rb
  benchmarks/shared.rb
  ext/llhttp/llhttp_ext.c
  lib/llhttp/delegate.rb
  spec/integration/parser/request_parsing/callback_errors_spec.rb
Labels: commit.changelog, commit.type.chg

#2 Support introspection of http major/minor version
  ext/llhttp/llhttp_ext.c
  lib/llhttp/parser.rb
  spec/integration/introspection/http_major_spec.rb
  spec/integration/introspection/http_minor_spec.rb
Labels: commit.changelog, commit.type.add

#9 Update llhttp to 4.0.0
  ext/llhttp/api.c
  ext/llhttp/llhttp.c
  ext/llhttp/llhttp.h
  spec/integration/callbacks/header_field_complete_spec.rb
Labels: commit.changelog, commit.type.chg

#10 Only setup callbacks if they are defined on the delegate
  ext/llhttp/llhttp_ext.c
  lib/llhttp/delegate.rb
Labels: commit.changelog, commit.type.chg

#11 Rename Parser#method to Parser#method_name
  ext/llhttp/llhttp_ext.c
  lib/llhttp/parser.rb
  spec/integration/introspection/method_name_spec.rb
Labels: commit.changelog, commit.type.chg

#13 Resolve an issue with the parser finalizer
  ffi/lib/llhttp/delegate.rb
  ffi/lib/llhttp/parser.rb
Labels: commit.changelog-ffi, commit.type.fix
